easy_admin:
  site_name : Heroes Corner
    entities:
        - App\Entity\BlogCategory
        - App\Entity\Category
        - App\Entity\Comment
        - App\Entity\Order
        - App\Entity\Post
        - App\Entity\Product
        - App\Entity\User