easy_admin:
    site_name : Heroes Corner 
    entities:
        Category:
            class: App\Entity\Category
           

        BlogCategory:
            class: App\Entity\BlogCategory
           
            
        Comment:
            class: App\Entity\Comment
            

        Order:
            class: App\Entity\Order
            
                
        Post:
            class: App\Entity\Post
            

        Product:
            class: App\Entity\Product


        User:
            class: App\Entity\User
           
                  